### ISSUE TITLE
求出的矩阵结果意义

### ISSUE THREAD

**Issue by CaffeMrDe** [ddl-hust/hand2eye#1]
矩阵求出的结果只是求出两个矩阵的 线性变换，没有特别说明在手眼标定的意义？ 

或者说没有在handToEye的时候，指出CamInBase 或者是 CalToTool的矩阵。

谢谢Up的git

**Comment by ddl-hust** [comment]
兄弟这个repo已经过去几个月了，我自己都有点不记得了，我这几天有空在看看
